# Generated by Django 4.0.4 on 2022-05-01 07:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmessage',
            name='messageBody',
            field=models.CharField(default=django.utils.timezone.now, max_length=5000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='whatsappmessage',
            name='messageSender',
            field=models.CharField(max_length=200),
        ),
    ]
